version: "3.9"
services:
  db:
    image: postgres:16.2
    restart: always
    ports:
      - 5432:5432
    container_name: handzone-db
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DB: handzone

  docker:
    image: tecnativa/docker-socket-proxy
    privileged: true
    environment:
      - CONTAINERS=1
      - ALLOW_START=1
      - ALLOW_STOP=1
      - ALLOW_RESTART=1
      - POST=1
    restart: always
    ports: 
      - "2375:2375"
    container_name: handzone-docker
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]

  app-dev:
    build:
      context: .
      dockerfile: dockerfile-dev
    env_file:
      - .env
    restart: always
    ports: 
      - "3000:3000"
    container_name: handzone-server-dev
    environment:
      VIRTUAL_HOST: ${HOSTNAME}
      DATABASE_URL: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db/handzone?schema=public"
    volumes:
      - type: bind
        source: ./config.json
        target: /app/config.json
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    depends_on:
      - db
      - docker

networks:
  default:
    name: ${DOCKER_NETWORK}

volumes:
  database: