version: "3.9"
services:
  db:
    image: postgres:16.2
    restart: always
    ports:
      - 5432:5432
    container_name: handzone-db
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DB: handzone

  app:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    restart: always
    ports: 
      - "3000:3000"
    container_name: handzone-server
    environment:
      VIRTUAL_HOST: ${HOSTNAME}
      DATABASE_URL: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db/handzone?schema=public"
    networks:
      - ${DOCKER_NETWORK}
    volumes:
      - type: bind
        source: /app/config.json
        target: /app/config.json
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

  docker:
    image: tecnativa/docker-socket-proxy
    environment:
      - CONTAINERS=1
      - ALLOW_START=1
      - ALLOW_STOP=1
      - ALLOW_RESTART=1
    container_name: handzone-docker
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ${DOCKER_NETWORK}
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  default:
    name: ${DOCKER_NETWORK}

volumes:
  database: