version: "3.9"
services:
  db:
    image: postgres:16.2
    restart: always
    ports:
      - 5432:5432
    container_name: handzone-db
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DB: handzone

  app:
    image: ghcr.io/newmedia-centre/handzone-server:latest
    env_file:
      - .env
    restart: always
    ports: 
      - "3000:3000"
    container_name: handzone-server
    environment:
      VIRTUAL_HOST: ${HOSTNAME}
      DATABASE_URL: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db/handzone?schema=public"
    volumes:
      - type: bind
        source: /app/config.json
        target: /app/config.json
      - type: bind
        source: /run/docker.sock
        target: /var/run/docker.sock

networks:
  default:
    name: ${DOCKER_NETWORK}

volumes:
  database: