// import components
import { Header } from './header'
import { Footer } from './footer'

// import styles
import { Inter } from 'next/font/google'
import './globals.css'

// import types
import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Handzone',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={'flex flex-col size-full container min-h-screen mx-auto ' + inter.className}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	)
}
