name: Build Polyscope for URSIM CB 3.15.8

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image and Push to Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          file: ./server/dockerfile-ursim
          context: ./server
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ursim_cb3:3.15.8